name: easy_formz_inputs
description: The easy_formz_inputs library provides pre-built, validated input fields for use in Dart and Flutter applications. Inputs currently provided include email, password, confirm password, urls, date, phone, and non-empty fields.
repository: https://github.com/Avila-Tek/easy_formz_inputs
issue_tracker: https://github.com/Avila-Tek/easy_formz_inputs/issues
homepage: https://github.com/Avila-Tek/easy_formz_inputs
documentation: https://github.com/Avila-Tek/easy_formz_inputs

version: 0.1.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  formz: ^0.6.0
  intl: ^0.18.0
  
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0
